export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCHING_DONE = "FETCHING_DONE";
export const FETCHING_FAILED = "FETCHING_FAILED";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT ";
export const ADD_TO_CART = "ADD_TO_CART";
export const SAVE_PRODUCT_TO_SHOW = "SAVE_PRODUCT_TO_SHOW";
export const SETTING_CHECKOUT_DETAILS = "SETTING_CHECKOUT_DETAILS";
export const PUSHING_IN_ADDRESS_ARRAY = "PUSHING_IN_ADDRESS_ARRAY";