export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCHING_SUCCESSFUL = "FETCHING_SUCCESSFUL";
export const FETCHING_UNSUCCESSFUL = "FETCHING_UNSUCCESSFUL";
export const ADD_PRODUCT = "ADD_PRODUCT";